// Auto-generated. Do not edit!

// (in-package spar_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class FlightMotionResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.final_position = null;
      this.final_yaw = null;
    }
    else {
      if (initObj.hasOwnProperty('final_position')) {
        this.final_position = initObj.final_position
      }
      else {
        this.final_position = new geometry_msgs.msg.Point();
      }
      if (initObj.hasOwnProperty('final_yaw')) {
        this.final_yaw = initObj.final_yaw
      }
      else {
        this.final_yaw = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FlightMotionResult
    // Serialize message field [final_position]
    bufferOffset = geometry_msgs.msg.Point.serialize(obj.final_position, buffer, bufferOffset);
    // Serialize message field [final_yaw]
    bufferOffset = _serializer.float32(obj.final_yaw, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FlightMotionResult
    let len;
    let data = new FlightMotionResult(null);
    // Deserialize message field [final_position]
    data.final_position = geometry_msgs.msg.Point.deserialize(buffer, bufferOffset);
    // Deserialize message field [final_yaw]
    data.final_yaw = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 28;
  }

  static datatype() {
    // Returns string type for a message object
    return 'spar_msgs/FlightMotionResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '4b3178d27ded286f74bb27991e7d5fea';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Result
    
    geometry_msgs/Point final_position	# Final commanded position
    float32 final_yaw					# Final commanded yaw
    
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FlightMotionResult(null);
    if (msg.final_position !== undefined) {
      resolved.final_position = geometry_msgs.msg.Point.Resolve(msg.final_position)
    }
    else {
      resolved.final_position = new geometry_msgs.msg.Point()
    }

    if (msg.final_yaw !== undefined) {
      resolved.final_yaw = msg.final_yaw;
    }
    else {
      resolved.final_yaw = 0.0
    }

    return resolved;
    }
};

module.exports = FlightMotionResult;
