// Auto-generated. Do not edit!

// (in-package spar_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class FlightMotionFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.progress = null;
      this.waiting_for_convergence = null;
      this.goal_position = null;
      this.goal_yaw = null;
    }
    else {
      if (initObj.hasOwnProperty('progress')) {
        this.progress = initObj.progress
      }
      else {
        this.progress = 0.0;
      }
      if (initObj.hasOwnProperty('waiting_for_convergence')) {
        this.waiting_for_convergence = initObj.waiting_for_convergence
      }
      else {
        this.waiting_for_convergence = false;
      }
      if (initObj.hasOwnProperty('goal_position')) {
        this.goal_position = initObj.goal_position
      }
      else {
        this.goal_position = new geometry_msgs.msg.Point();
      }
      if (initObj.hasOwnProperty('goal_yaw')) {
        this.goal_yaw = initObj.goal_yaw
      }
      else {
        this.goal_yaw = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type FlightMotionFeedback
    // Serialize message field [progress]
    bufferOffset = _serializer.float32(obj.progress, buffer, bufferOffset);
    // Serialize message field [waiting_for_convergence]
    bufferOffset = _serializer.bool(obj.waiting_for_convergence, buffer, bufferOffset);
    // Serialize message field [goal_position]
    bufferOffset = geometry_msgs.msg.Point.serialize(obj.goal_position, buffer, bufferOffset);
    // Serialize message field [goal_yaw]
    bufferOffset = _serializer.float32(obj.goal_yaw, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type FlightMotionFeedback
    let len;
    let data = new FlightMotionFeedback(null);
    // Deserialize message field [progress]
    data.progress = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [waiting_for_convergence]
    data.waiting_for_convergence = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [goal_position]
    data.goal_position = geometry_msgs.msg.Point.deserialize(buffer, bufferOffset);
    // Deserialize message field [goal_yaw]
    data.goal_yaw = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 33;
  }

  static datatype() {
    // Returns string type for a message object
    return 'spar_msgs/FlightMotionFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6f23ddce6055aec8d4fbc59ea65c4cb8';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    
    # Feedback
    
    float32 progress					# Progress 0..1 from start to goal
    bool waiting_for_convergence		# Mark to show if waiting for convergence
    
    geometry_msgs/Point goal_position	# Current goal position
    float32 goal_yaw					# Current goal yaw
    
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new FlightMotionFeedback(null);
    if (msg.progress !== undefined) {
      resolved.progress = msg.progress;
    }
    else {
      resolved.progress = 0.0
    }

    if (msg.waiting_for_convergence !== undefined) {
      resolved.waiting_for_convergence = msg.waiting_for_convergence;
    }
    else {
      resolved.waiting_for_convergence = false
    }

    if (msg.goal_position !== undefined) {
      resolved.goal_position = geometry_msgs.msg.Point.Resolve(msg.goal_position)
    }
    else {
      resolved.goal_position = new geometry_msgs.msg.Point()
    }

    if (msg.goal_yaw !== undefined) {
      resolved.goal_yaw = msg.goal_yaw;
    }
    else {
      resolved.goal_yaw = 0.0
    }

    return resolved;
    }
};

module.exports = FlightMotionFeedback;
