#!/usr/bin/python3
import RPi.GPIO as GPIO
import time

SERVO_PIN = 12

GPIO.setmode(GPIO.BCM)
GPIO.setup(SERVO_PIN, GPIO.OUT)

pwm = GPIO.PWM(SERVO_PIN, 50)
pwm.start(0)

def set_angle(angle):
	duty=(angle/18.0) + 2.5
	GPIO.output(SERVO_PIN, True)
	pwm.ChangeDutyCycle(duty)
	time.sleep(0.5)
	GPIO.output(SERVO_PIN, False)
	pwm.ChangeDutyCycle(0)

try:
	while True:
		print("starting...")
		set_angle(0)
		time.sleep(1)
		set_angle(90)
		print("turning...")
		time.sleep(1)
		set_angle(180)
		print("turning2...")
		time.sleep(1)

except KeyboardInterrupt:
	pwm.stop()
	GPIO.cleanup()
