// Generated by gencpp from file breadcrumb/RequestPath.msg
// DO NOT EDIT!


#ifndef BREADCRUMB_MESSAGE_REQUESTPATH_H
#define BREADCRUMB_MESSAGE_REQUESTPATH_H

#include <ros/service_traits.h>


#include <breadcrumb/RequestPathRequest.h>
#include <breadcrumb/RequestPathResponse.h>


namespace breadcrumb
{

struct RequestPath
{

typedef RequestPathRequest Request;
typedef RequestPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestPath
} // namespace breadcrumb


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::breadcrumb::RequestPath > {
  static const char* value()
  {
    return "01fd153fe570128ee975daa9976a93a4";
  }

  static const char* value(const ::breadcrumb::RequestPath&) { return value(); }
};

template<>
struct DataType< ::breadcrumb::RequestPath > {
  static const char* value()
  {
    return "breadcrumb/RequestPath";
  }

  static const char* value(const ::breadcrumb::RequestPath&) { return value(); }
};


// service_traits::MD5Sum< ::breadcrumb::RequestPathRequest> should match
// service_traits::MD5Sum< ::breadcrumb::RequestPath >
template<>
struct MD5Sum< ::breadcrumb::RequestPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::breadcrumb::RequestPath >::value();
  }
  static const char* value(const ::breadcrumb::RequestPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::breadcrumb::RequestPathRequest> should match
// service_traits::DataType< ::breadcrumb::RequestPath >
template<>
struct DataType< ::breadcrumb::RequestPathRequest>
{
  static const char* value()
  {
    return DataType< ::breadcrumb::RequestPath >::value();
  }
  static const char* value(const ::breadcrumb::RequestPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::breadcrumb::RequestPathResponse> should match
// service_traits::MD5Sum< ::breadcrumb::RequestPath >
template<>
struct MD5Sum< ::breadcrumb::RequestPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::breadcrumb::RequestPath >::value();
  }
  static const char* value(const ::breadcrumb::RequestPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::breadcrumb::RequestPathResponse> should match
// service_traits::DataType< ::breadcrumb::RequestPath >
template<>
struct DataType< ::breadcrumb::RequestPathResponse>
{
  static const char* value()
  {
    return DataType< ::breadcrumb::RequestPath >::value();
  }
  static const char* value(const ::breadcrumb::RequestPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BREADCRUMB_MESSAGE_REQUESTPATH_H
