// Generated by gencpp from file breadcrumb/RequestPathRequest.msg
// DO NOT EDIT!


#ifndef BREADCRUMB_MESSAGE_REQUESTPATHREQUEST_H
#define BREADCRUMB_MESSAGE_REQUESTPATHREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace breadcrumb
{
template <class ContainerAllocator>
struct RequestPathRequest_
{
  typedef RequestPathRequest_<ContainerAllocator> Type;

  RequestPathRequest_()
    : start()
    , end()  {
    }
  RequestPathRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , end(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _end_type;
  _end_type end;





  typedef boost::shared_ptr< ::breadcrumb::RequestPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::breadcrumb::RequestPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RequestPathRequest_

typedef ::breadcrumb::RequestPathRequest_<std::allocator<void> > RequestPathRequest;

typedef boost::shared_ptr< ::breadcrumb::RequestPathRequest > RequestPathRequestPtr;
typedef boost::shared_ptr< ::breadcrumb::RequestPathRequest const> RequestPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::breadcrumb::RequestPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::breadcrumb::RequestPathRequest_<ContainerAllocator1> & lhs, const ::breadcrumb::RequestPathRequest_<ContainerAllocator2> & rhs)
{
  return lhs.start == rhs.start &&
    lhs.end == rhs.end;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::breadcrumb::RequestPathRequest_<ContainerAllocator1> & lhs, const ::breadcrumb::RequestPathRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace breadcrumb

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::breadcrumb::RequestPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::breadcrumb::RequestPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::breadcrumb::RequestPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad6f4eea34a193d38008f1d4053cce66";
  }

  static const char* value(const ::breadcrumb::RequestPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad6f4eea34a193d3ULL;
  static const uint64_t static_value2 = 0x8008f1d4053cce66ULL;
};

template<class ContainerAllocator>
struct DataType< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "breadcrumb/RequestPathRequest";
  }

  static const char* value(const ::breadcrumb::RequestPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Calculates a path between two points\n"
"# Request:\n"
"#   start:\n"
"#     - Starting point on the grid (in meters)\n"
"#     - Z value is ignored\n"
"#     - In the grids parent frame\n"
"#   end:\n"
"#     - Ending point on the grid (in meters)\n"
"#     - Z value is ignored\n"
"#     - In the grids parent frame\n"
"\n"
"geometry_msgs/Point start\n"
"geometry_msgs/Point end\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::breadcrumb::RequestPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.end);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::breadcrumb::RequestPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::breadcrumb::RequestPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "end: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.end);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BREADCRUMB_MESSAGE_REQUESTPATHREQUEST_H
