(cl:defpackage spar_msgs-msg
  (:use )
  (:export
   "<FLIGHTMOTIONACTION>"
   "FLIGHTMOTIONACTION"
   "<FLIGHTMOTIONACTIONFEEDBACK>"
   "FLIGHTMOTIONACTIONFEEDBACK"
   "<FLIGHTMOTIONACTIONGOAL>"
   "FLIGHTMOTIONACTIONGOAL"
   "<FLIGHTMOTIONACTIONRESULT>"
   "FLIGHTMOTIONACTIONRESULT"
   "<FLIGHTMOTIONFEEDBACK>"
   "FLIGHTMOTIONFEEDBACK"
   "<FLIGHTMOTIONGOAL>"
   "FLIGHTMOTIONGOAL"
   "<FLIGHTMOTIONRESULT>"
   "FLIGHTMOTIONRESULT"
  ))

