; Auto-generated. Do not edit!


(cl:in-package spar_msgs-msg)


;//! \htmlinclude FlightMotionResult.msg.html

(cl:defclass <FlightMotionResult> (roslisp-msg-protocol:ros-message)
  ((final_position
    :reader final_position
    :initarg :final_position
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point))
   (final_yaw
    :reader final_yaw
    :initarg :final_yaw
    :type cl:float
    :initform 0.0))
)

(cl:defclass FlightMotionResult (<FlightMotionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FlightMotionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FlightMotionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name spar_msgs-msg:<FlightMotionResult> is deprecated: use spar_msgs-msg:FlightMotionResult instead.")))

(cl:ensure-generic-function 'final_position-val :lambda-list '(m))
(cl:defmethod final_position-val ((m <FlightMotionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader spar_msgs-msg:final_position-val is deprecated.  Use spar_msgs-msg:final_position instead.")
  (final_position m))

(cl:ensure-generic-function 'final_yaw-val :lambda-list '(m))
(cl:defmethod final_yaw-val ((m <FlightMotionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader spar_msgs-msg:final_yaw-val is deprecated.  Use spar_msgs-msg:final_yaw instead.")
  (final_yaw m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FlightMotionResult>) ostream)
  "Serializes a message object of type '<FlightMotionResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'final_position) ostream)
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'final_yaw))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FlightMotionResult>) istream)
  "Deserializes a message object of type '<FlightMotionResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'final_position) istream)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'final_yaw) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FlightMotionResult>)))
  "Returns string type for a message object of type '<FlightMotionResult>"
  "spar_msgs/FlightMotionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FlightMotionResult)))
  "Returns string type for a message object of type 'FlightMotionResult"
  "spar_msgs/FlightMotionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FlightMotionResult>)))
  "Returns md5sum for a message object of type '<FlightMotionResult>"
  "4b3178d27ded286f74bb27991e7d5fea")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FlightMotionResult)))
  "Returns md5sum for a message object of type 'FlightMotionResult"
  "4b3178d27ded286f74bb27991e7d5fea")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FlightMotionResult>)))
  "Returns full string definition for message of type '<FlightMotionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%~%geometry_msgs/Point final_position	# Final commanded position~%float32 final_yaw					# Final commanded yaw~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FlightMotionResult)))
  "Returns full string definition for message of type 'FlightMotionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%~%geometry_msgs/Point final_position	# Final commanded position~%float32 final_yaw					# Final commanded yaw~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FlightMotionResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'final_position))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FlightMotionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FlightMotionResult
    (cl:cons ':final_position (final_position msg))
    (cl:cons ':final_yaw (final_yaw msg))
))
